name: Java CI

on:
  - push
  - pull_request

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./app
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
      - uses: gradle/actions/setup-gradle@v4
        with:
          gradle-version: 8.7
      - uses: gradle/gradle-build-action@v2
        with:
          arguments: build
          build-root-directory: app
      - name: Publish code coverage
        uses: paambaati/codeclimate-action@v3.1.1
        env:
          CC_TEST_REPORTER_ID: ${{secrets.CC_TEST_REPORTER_ID}}
          JACOCO_SOURCE_PATH: app/src/main/java
        with:
          build-root-directory:
          coverageCommand: make report
          coverageLocations: /home/runner/work/java-project-71/app/build/reports/jacoco/test/jacocoTestReport.xml:jacoco
      # - name: Publish code coverage
      #   uses: paambaati/codeclimate-action@v9.0.0
      #   env:
      #     CC_TEST_REPORTER_ID: ${{secrets.CC_TEST_REPORTER_ID}}
      #     JACOCO_SOURCE_PATH: /home/runner/work/java-project-71/src/main/java
      #   with:
      #     coverageCommand: make report
      #     coverageLocations: /home/runner/work/java-project-71/build/reports/jacoco/test/jacocoTestReport.xml:jacoco
